import Header from '@/Components/Header'
import NavBar from '@/Components/NavBar'
import './globals.css'

export const metadata = {
  title: 'Imdb Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body>
          <Header />
          <NavBar />
          <main> {children}</main>
        </body>
      </html>
    </>
  )
}
